### PR TITLE
Add login, passcode, host optional headers to CONNECT frame

### PR DESCRIPTION
**Pull request by Dumbris**
According to http://stomp.github.io/stomp-specification-1.1.html#CONNECT_or_STOMP_Frame

### CODE REVIEW

**Comment by michaelkrog** [comment]
Hmm.  Wait up.. I'll merge this in and make the changes I just mentioned.

**Comment by Dumbris** [comment]
My mistake, I forgot to add _header['host'] = 
line

STOMP spec describe host header as mandatory for 1.1 version. It is ok, to get default host value from socketadapter, and not to force user set it up. But with ability to override it via connect() parameters.

Also note, in really, this is a "virtual host". In my project, I use RabbitMQ with STOMP plugin. And "virtual host" in RabbitMQ provide a way to segregate applications using the same server instance. Also, users can be assigned permissions to specific virtual hosts providing the ability to grant rights. I suppose in other STOMP server implementations virtual host does the same.

**Comment by michaelkrog** [comment]
Ok. I would just think that the StompClient is so connected to the underlying websocket(or TCP socket), that the url for the socket would almost always point to the same virtual host.

So, just to confirm.

The url you use for the socket does normally NOT contain the same host name as the one you would use in the StompClient?

**Comment by michaelkrog** [comment]
Hmm.  No matter the how its normally used, having a named parameter for host - as you suggested - seems reasonable enough.  I'll add it..

**Comment by Dumbris** [comment]
Ok, thank you.

In rabbitmq virtual hosts is AMQP concept. Usually writen as "/myvhost", the default virtual host is "/"

**Pull request merged**
